### ISSUE TITLE
Croner & PM2: Croner job is stopping at 00:00

### ISSUE THREAD

**Issue by oom-** [Hexagon/croner#102]
Hello, 
I'm using [pm2](https://www.npmjs.com/package/pm2) to keep my services up and running and centralize logs.

I'm running actually a really simple piece of code in a docker container (basically theses commands appears in my `Dockerfile`):
```docker
FROM node:16.15-bullseye-slim
COPY release /opt/src/publisher
CMD pm2 start /opt/src/bot/main.js --time  -o /var/log/publisher/publisher.log -e /var/log/publisher/publisher.log ; pm2 logs
```

Here is my NodeJS code: 
```js
const dayjs = require('dayjs');
const Cron = require("croner");

//Simple match wildcard function like: "aa" will match "a*" or "*a" or "**" but not "bb" or "b*"
function matchWildcard(str1, str2) {
    if (typeof str1 != "string" || typeof str2 != "string")
        return false;
    if (str1.length != str2.length)
        return false;
    for (let i = 0; i < str1.length; i++) {
        if (str1.at(i) != "*" && str2.at(i) != "*" && str1.at(i) != str2.at(i)) {
            console.debug(`${str1} matchs ${str2} ?: FALSE`);
            return false;
        }
    }
    console.debug(`${str1} matchs ${str2} ?: TRUE`);
    return true;
}

//My cron task running every minute
const job = Cron("0 */1 * ? * *", async () => {
    let now = dayjs();
    let dayKey = now.format("HH:mm.DD-MM");
    matchWildcard("12:00.27-**", dayKey);
});
```

So the croner job is starting but stops at 00:00 and I do not know why this append:
![image](https://user-images.githubusercontent.com/11071671/170886078-04b4d750-d1fa-4ce5-a28c-6e1dd700170d.png)

**Comment by Hexagon** [comment]
? A question mark is substituted with croner initialization time, as an example - ? ? * * * * would be substituted with 25 8 * * * * if time is <any hour>:08:25 at the time of new Cron('? ? * * * *', <...>). The question mark can be used in any field.

The questionmark in your example is substituted with the current date of month, and the expression is paused for a month before running again.

**Comment by oom-** [comment]
Omg. You are right. My bad, because of the #101 I opened I though it was related with PM2 as well.
I thought it worked already one time but I probably restart my docker at 00:01 past day without figuring out.
I generated this cron with this website to avoid errors: [cronmaker.com](cronmaker.com). So definitely not recommended.

Sorry for the inconvenience.
