### ISSUE TITLE
Duplicate executing

### ISSUE THREAD

**Issue by valeriythedev** [Hexagon/croner#117]
Hello, i have duplicate executing issue with croner,
![image](https://user-images.githubusercontent.com/77352085/179226153-a09a05f3-32cb-476b-aca5-17fac7d4f854.png)
importing
![image](https://user-images.githubusercontent.com/77352085/179226190-faab233c-6548-4c2c-8c87-09ea07d4be64.png)
code
![image](https://user-images.githubusercontent.com/77352085/179226243-791383aa-fcd1-4330-8fa1-a0c87c783079.png)
results
as i understand right, i place maxRuns:1 and interval in options, but same result its sending a lot of request, but needed to send only one
same situation with cron, node-schedule

**Comment by Hexagon** [comment]
With maxRuns:1 croner should only execute the function once. Are you sure that useEffect isnt triggered multipla times? Could you make a console.log before const job = ... to rule out multiple instances of croner?

**Comment by valeriythedev** [comment]
Yes, its executing multiple times in useEffect
![image](https://user-images.githubusercontent.com/77352085/179231919-9d51cec8-6174-4ea3-a689-60fc629e702e.png)
but same situation without useEffect
![image](https://user-images.githubusercontent.com/77352085/179231994-cbf36681-52ec-47c8-8be8-de21ea067f38.png)
