### ISSUE TITLE
Cronjob with long timeouts...

### ISSUE THREAD

**Issue by TomFuch** [Hexagon/croner#118]
I will use Croner for a nodejs console app. Handle Croner also long timeouts for running jobs every 4 Months?

**Comment by Hexagon** [comment]
Yes, it does support long timeouts. But as croner does not have a backend of it's own, execution wil be missed if the program is down at the time of execution.

**Comment by TomFuch** [comment]
> Yes, it does support long timeouts. But as croner does not have a backend of it's own, execution wil be missed if the program is down at the time of execution.

Thank you for your quick Answer!
p.s. Croner does had realy cool features! 👏
