### ISSUE TITLE
Feature request: onComplete callback

### ISSUE THREAD

**Issue by cjohansen11** [Hexagon/croner#130]
This is more of a question and/or possible feature request. Does Croner have an `onComplete` type callback ability? Essentially I'm looking to run this job x amount of times using `maxRuns` however on the last run if my tasks are not complete I will need to perform other tasks. So without keeping an internal count of the runs and then running if it hits its max I would like to use the `maxRuns` option and then pass another callback function to on if `maxRuns` has reached it's end. Thanks!

**Comment by Hexagon** [comment]
There is no such functionality right now, but there is a simple solution to try. 

The job will be passed as the first parameter to the triggered function, use that and check for `if(job.next()===null) // this os the last run`.

**Comment by cjohansen11** [comment]
> 

Ah great, that seems like it should work. I was also going to try using `job.options.maxRuns === 0` which could have worked too. Appreciate the quick feedback!!

**Comment by Hexagon** [comment]
Cool! Keep us updated on which path you choose, and leave the issue open.

**Comment by Hexagon** [comment]
I've looked into this a bit deeper now. I actually think one of the simplest and cleanest solutions would be to implement this in this where it's needed. Something like:

```javascript
import Cron from "croner";

const job = new Cron("0/5 * * * * *", { maxRuns: 2 }, (job) => {
    
    // Do work
    console.log('Job Running');

    // Is this the last execution?
    if (!job.next()) {
        console.log('Last execution');
    }

});
 
// Will there be no executions?
if (!job.next() && !job.previous()) {
    console.log('No executions scheduled');
}
```

**Comment by Hexagon** [comment]
Fixed by new example in docs at https://github.com/Hexagon/croner#act-at-completion
