### ISSUE TITLE
Proper types support for ESM exports when moduleResolution is set to NodeNext (^TS 4.7)

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Hexagon/croner#136]
Hi, 

first of all thanks for this package. I noticed that the package itself is already a `module` which is really nice. But unfortunately there are some minor things which needs to be updated to support `NodeNext` as `moduleResolution`. 

The problem is easy to reproduce: 
- Create a TypeScript project
- Have a tsconfig in place and set the `moduleResolution` to `NodeNext`
- Install croner 
- import croner in index.ts 

As you will notice, the types cannot be resolved.

This configuration in TypeScript is really strict about some settings and cannot detect types in a fallback manner (`types` field). Therefore you need to update the `package.json` like documented here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing 

This would mean the `package.json` should look like this: 

``` json
 {
  "type": "module",
  "main": "./dist/croner.cjs",
  "browser": "./dist/croner.min.js",
  "module": "./src/croner.js",
  "types": "types/croner.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "types": "./types/croner.d.ts",
        "default": "./src/croner.js"
      },
      "require": "./dist/croner.cjs",
      "browser": "./dist/croner.min.js"
    },
    "./minified": {
      "import": "./dist/croner.min.mjs",
      "require": "./dist/croner.min.js",
      "browser": "./dist/croner.min.js",
      "types": "./types/croner.d.ts"
    }
  }
}
```

So instead of relying on the old field `types` we need to define the types explicit for the `import` mapping. This way the types can be properly resolved (but only when defined as first prop in the `import` object).

I tested the changes locally and they work well. Hope it can be fixed pretty soon, but for now I just add the types via `include` in the `tsconfig` file as workaround.

**Comment by Hexagon** [comment]
Great research, thanks!

If you summit a PR with a modified package.json and version bumped to 5.0.1, i can publish a new version instantly. Otherwise i'll fix it at next release 👍

**Comment by Sebastian-Fitzner** [comment]
Will do, thx for the quick response!

**Comment by Hexagon** [comment]
@Sebastian-Fitzner Works ok with croner@5.0.1 ?

**Comment by Sebastian-Fitzner** [comment]
@Hexagon Thanks a lot! It is working, I would have created one until the end of the week ;).
