### ISSUE TITLE
Wrong evaluation of dayOfWeek AND dayOfMonth

### ISSUE THREAD

**Issue by vbargl** [Hexagon/croner#139]
Expression `0 0 0 13 * 5` does not generate right dates.
This is basically expression for https://en.wikipedia.org/wiki/Friday_the_13th.

Croner generates (for 2023 - [source](https://runkit.com/vbargl/632d6b330b3140000868093d))
```
0: Fri Jan 06 2023
1: Fri Jan 13 2023
2: Fri Jan 20 2023
...
6: Mon Feb 13 2023
```

but expected would be (for 2023 - [source](https://www.timeanddate.com/calendar/weekday-friday-13))
```
0: Fri, Jan 13 2023
1: Fri, Oct 13 2023
2: Fri, Sep 13 2024
3: Fri, Dec 13 2024
4: Fri, Jun 13 2025
...
```

As you can see from examples dayOfMonth and dayOfWeek combination behaves as OR instead of AND.

**Comment by Hexagon** [comment]
OR is default since 5.0.0, but can be changed to and by supplying option legacyMode: false

See https://github.com/Hexagon/croner/issues/53

**Comment by vbargl** [comment]
Ah. Super nice! I thought I need to set legacyMode to true.
And honestly I thought cron would behave with AND not OR.

Thanks for quick reply.
