### ISSUE TITLE
Code size vs readability

### ISSUE THREAD

**Issue by egfx-notifications** [Hexagon/croner#143]
It has been a few months since I was last able to keep track of the developments in croner. Reading up on the changes (and there have been a lot of nice improvements!) I'd like to debate whether the changes to variable names in https://github.com/Hexagon/croner/commit/390ebcadb5ba98cc7c4843dc9aaa831477bae09e are really a good trade-off.  
While it certainly makes the code size smaller, I think it also makes the code less readable. I always thought of croner as a very well written, easy to understand library. So I'm afraid this change will introduce some tribal knowledge to the code which makes it harder for future contributors to get up to speed. Being a backend developer, I do not usually care that much about binary size, so maybe it is worth the reduction in readability and I'm just wrong. Still I'm wondering if there would not be a better solution for this (uglify, etc.) which provides small code size for shipping the code while keeping the code nice and clear for development. At least we could make sure that all those shorthand property names have solid doc comments.

**Comment by Hexagon** [comment]
You're totally right. The difference were 300 bytes (!)... Will restore some of the changes, and also add some missing JSDocs :)

**Comment by Hexagon** [comment]
Fixed in 843208ecf7f0a9e3802a3575aa5cd83ecb315874
