### ISSUE TITLE
Feature: Over-run protection (Was: How detect overlapping?)

### ISSUE THREAD

**Issue by alainrc2005** [Hexagon/croner#150]

**Comment by Hexagon** [comment]
You'll need to add some background so i can have a look at that. What du you want to achieve?

**Comment by Hexagon** [comment]
Closing for now, as open issues are primarily for active bugs.

**Comment by kibertoad** [comment]
@alainrc2005 You can use https://github.com/kibertoad/toad-scheduler, it adds overrun protection on top of croner.

**Comment by Hexagon** [comment]
Reopening this as the feature is now work in progress

**Comment by Hexagon** [comment]
Released in `5.7.0`
