### ISSUE TITLE
msToNext() is a negative number

### ISSUE THREAD

**Issue by Steiger04** [Hexagon/croner#155]
msToNext() becomes negative if the cron is paused and the next cron call would actually be due in that time. After a resume() then msToNext() is negative. Did I just not understand the logic or is this a bug? I actually expected a positive value after resume() at msToNext(), which outputs the distance in ms to the next cron.

**Comment by Hexagon** [comment]
Thanks for the report! That seem to be a bug, looking into it right now.

**Comment by Hexagon** [comment]
(Hopefully) resolved in `5.4.1` which will be released any minute 👍

**Comment by Steiger04** [comment]
Error no longer occurs. Thanks for the super fast troubleshooting!
