### ISSUE TITLE
Feature: add a list of scheduled jobs

### ISSUE THREAD

**Issue by MZPL** [Hexagon/croner#160]
Hi, it's me again. Like other cron packages, I suggest exposing a list of scheduled jobs, which would allow users to control all of them in one place. For example, it'd be possible to find a job by its name and call `pause()`, `resume()`, `fn()`, etc. on it.
I could make a PR for this if you're interested in it :)

**Comment by Hexagon** [comment]
Hi! Sounds interesting! A PR would be very welcome :+1:

**Comment by Hexagon** [comment]
Have a look at the [contribution guide](https://github.com/Hexagon/croner/blob/master/CONTRIBUTING.md) and try to keep it simple, and all will go smooth :rocket:
