### ISSUE TITLE
How to clean up side effects?

### ISSUE THREAD

**Issue by khromov** [Hexagon/croner#162]
👋 I saw that you can run `.stop()` on a job to stop it, and I wonder if this is enough to clean up any side effects? For example if you are in a client side application (React, Svelte, etc) and you need to completely delete a Croner job because the user navigates to another page where the job is no longer relevant.

I'm looking for something similar to `clearInterval()`.

**Comment by Hexagon** [comment]
Hi! 

`stop()` is effectively doing a clearTimeout internally, so after stopping, so there will be no lingering function calls.

Whats left after that is only the job instance, do that cause a problem with the frameworks?

**Comment by khromov** [comment]
:wave: Great! In this case setting the Croner instance variable to `undefined` should make it eligible for garbage collection.

Thank you for the info and for the great library, we use it in many places both on the client and on the server.

**Comment by Hexagon** [comment]
@khromov Thanks to you too! This made me think and make some adjustments. 

Currently, for a few versions, all job instances are stored in a common array called 'scheduledJobs,' which prevents Garbage Collection (GC) no matter what.

Starting from version `5.6.0` (released just nu), jobs are only stored if you give the job a name through the option 'name: ...'. This will make jobs be eligible for GC by default when they go out of scope.

I'm not sure how various front-end frameworks handle this, but setting the job instance to 'undefined' after running '.stop()' will still be the safest option.

See this new section of the readme - https://github.com/Hexagon/croner/blob/master/README.md#naming-jobs
