### ISSUE TITLE
Bug & Question: Handling of named jobs

### ISSUE THREAD

**Issue by Gabriel3232** [Hexagon/croner#172]
Hey, two questions:

1. In the cron entrypoint function, the check to see if the name is already registered is done after the job gets possibly scheduled (if provided with a function). If an error is thrown, I would expect the job to not have been scheduled. Would it make more sense to change the order so the name checked is done before possibly registering the job?

2. When calling `job.stop()`, the job can't be scheduled anymore but it is not removed from the `scheduledJobs` array. Meaning a Job with the same name can't be registered anymore without throwing an error. Is the user expected to manage the array or it could be removed in the stop function?

**Comment by Hexagon** [comment]
1. Nice finding, will fix asap!

2. There could be use cases where it's usable to leave the job in the array, so that the user can see that the job has existed but is stopped. However, it would be nice to have an additional method `.destroy()` which unlinks the job from the array, allowing it to be re-registered and garbage-collected. Will put this on the to-do-list if you're not up to it (?).

**Comment by Hexagon** [comment]
1. Fixed in `6.0.1`

**Comment by Gabriel3232** [comment]
> There could be use cases where it's usable to leave the job in the array, so that the user can see that the job has existed but is stopped

I don't think there's a way right now to check is a Job has been stopped. To support that use case, would a new method like this makes sense?
```typescript
isStopped() {
    return this._states.kill;
}
```

**Comment by Hexagon** [comment]
Yep, that would make sense 👍

**Comment by Gabriel3232** [comment]
Unless you want to tackle this sooner, can probably make a PR before end of week

**Comment by Hexagon** [comment]
Working on this right now 🏗️

**Comment by Hexagon** [comment]
Pre-released in https://github.com/Hexagon/croner/releases/tag/6.0.2-dev.0
