### ISSUE TITLE
Error on calling imported function

### ISSUE THREAD

**Issue by namandureja** [Hexagon/croner#177]
**Describe the bug**
I am trying to schedule a job that uses an external function getProgramme which takes in parameter user.email. And this error is being thrown - 
<img width="687" alt="Screenshot 2023-03-27 at 2 19 42 AM" src="https://user-images.githubusercontent.com/58641903/227803803-c76415af-cbcd-423d-be30-fa42a4dbc736.png">
TypeError: (0 , user_1.getProgramme) is not a function
    at Cron.<anonymous> (/Users/ndureja/development/pocket-i/api/utils/notification.ts:39:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ndureja/development/pocket-i/api/utils/notification.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**To Reproduce**
```
import { getProgramme } from "../routes/user";

Cron("*/1 * * * *", {}, async function () {
    // get all users
    const users = await User.find();
    // loop through all users
    for (const user of users) {
        // get programme for users
        try {
            getProgramme(user.email).then((prg)=>{ .......});
       } catch (e){
            console.log(e);
       }
     }
})
```

**System:**
 - OS: MacOs
 - Runtime: NodeJs

**Comment by Hexagon** [comment]
I do not think that has anything to do with croner, what does ```typeof getProgramme``` output?

**Comment by namandureja** [comment]
getProgramme takes in user's email and returns a string. 
Here's an abstract implementation - 
```
export const getProgramme = async (email: string) : Promise<string> => {
    let program = await Program.findOne({ email });
    return program.label;
};
```

**Comment by Hexagon** [comment]
Do

```ts
import { getProgramme } from "../routes/user";
getProgramme(user.email).then((prg)=>{ .......});
```

work?

**Comment by namandureja** [comment]
Okay got it, really sorry for the trouble.
