### ISSUE TITLE
Week days triggering on wrong days (0 0 12 ? * MON)

### ISSUE THREAD

**Issue by victornpb** [Hexagon/croner#180]
**Describe the bug**

I'm trying to schedule tasks to run on specific days of the week at a certain time.

Examples:
- Every Monday at 12:00 (0 0 12 ? * MON)
- Every Friday at 6:00  (0 0 6 ? * FRI)
- Every Sunday at 00:00 (0 0 0 ? * SUN)

I'm aware of the AND/OR `legacyMode` flag, but in that case I'm NOT specifying both weekday and day of month, I only care about weekday.

**To Reproduce**

I made a whole playground trying to reproduce the issue 

https://victornpb.github.io/cron/#0_0_12_?_*_FRI&

**Expected behavior**

Run once on every calendar day of the week

Example: `0 0 12 ? * FRI`

<img width="226" alt="image" src="https://user-images.githubusercontent.com/3372598/231922320-30b2179e-64f7-449d-b091-249d52795cec.png"><img width="221" alt="image" src="https://user-images.githubusercontent.com/3372598/231922649-13a7ad74-82f1-4ba0-b7ee-6f1839fc512f.png">

According to the calendar it would be day 14,21,28,5,12,19,26...

<img width="434" alt="image" src="https://user-images.githubusercontent.com/3372598/231922383-0fb8af2b-ceef-45d0-a78e-f852f6b95742.png">

Why is there a Saturday there?

And for some odd reason if I set `lagacyMode=false`, it only triggers on day 13?!
https://victornpb.github.io/cron/#0_0_12_?_*_FRI&legacyMode:false

<img width="468" alt="image" src="https://user-images.githubusercontent.com/3372598/231922881-6f3a2df0-83e4-431d-9e7a-cb464807b8ec.png">

According to every cron expression generator I tried this is not the expected behavior
https://www.freeformatter.com/cron-expression-generator-quartz.html

**System:**
 - OS: MacOS, Linux
 - Runtime Node.js, Chrome
 - Version Node 18, Chrome 111

**Comment by Hexagon** [comment]
Hello 👋 

As croner supports both legacy and bon legacy mode `?`

**Comment by victornpb** [comment]
I understand that the `?` is non standard like theres no spec behind it,
but looks like in the wild they all kinda agree what it should do.
I'm curious if any other character could have been chosen for current time, like `$` or `%` or `&`.

Because all libraries I found that parse or generate cron expressions, generates `0_0_0_?_*_SUN` and don't even accept `0_0_0_*_*_SUN`, so thats kinda of a bummer.

Aside from that I hope, this tool can be useful to the community here, to be able to easily share,
reproduction cases and illustrate issues.
https://victornpb.github.io/cron/#0_0_0_*_*_SUN&legacyMode:true

**Comment by Hexagon** [comment]
I'll consider that until next major release 👍 

Yeah, that looks like a useful tool, great work 🚀
