### ISSUE TITLE
Typo / incorrect way of importing Cron with CommonJS in the documentation

### ISSUE THREAD

**Issue by iisalazar** [Hexagon/croner#184]
Hey, there! I'm not sure how to raise this properly, I was about to create an issue about the docs, but anyways,,,

According to the [installation](https://github.com/Hexagon/croner#installation) section, if one is using CommonJS Require, you have to import the entire thing from croner, but it should be just the "Croner" instance. 

The example code should be 
```javascript
// ESM Import ...
import { Cron } from "croner";

// ... or CommonJS Require, need to desctructure it
const { Cron } = require("croner"); 
```

I think the docs could be improved further, and it should be changed that way. I would be glad to contribute to it honestly

**Comment by Hexagon** [comment]
Great feedback! I do not use CommonJS very often, so I guess all commonjs references should be checked. 

Do you want to submit a pull request fixing this?

**Comment by iisalazar** [comment]
@Hexagon 
Good point! The reason why I prefer the dereferenced version is because that one gives or has strong type hints, while the circular reference one does not.

Here's a screenshot of the strong type hints that you get using dereferenced vs the other one. I'm using VS Code as my editor

![Screenshot from 2023-05-18 03-04-43](https://github.com/Hexagon/croner/assets/19862244/f1361fb8-3346-4b32-9d84-8002ab845b00)
![Screenshot from 2023-05-18 03-05-08](https://github.com/Hexagon/croner/assets/19862244/2c5d61bd-d07c-4ce8-a908-2960138a1328)

Again, I would be glad to submit a PR for this. I want to hear your thoughts first

**Comment by Hexagon** [comment]
I see, and fully agree with you when seeing that! Go ahead with a PR if you like to👍

**Comment by iisalazar** [comment]
Got it, thanks @Hexagon !
