### ISSUE TITLE
background tasks 

### ISSUE THREAD

**Issue by ayahyaouiOEM** [Hexagon/croner#201]
The task doesn't work in the background (it work only when the script is running.
Is there a solution for this issue plz?

**Comment by Hexagon** [comment]
Provide more info, are you running in browser, which browser, what type of task are you trying to run?

Browsers do throttle activity in background tasks, and going around this is a bit tricky

**Comment by ayahyaouiOEM** [comment]
My app is running in chrome, and I have to send an automatic email with attachment in many pages of my react js app. 
The problem is that the schedule disappears when the execution is completed so only the active page executes the scheduled task for this reason I need for scheduling many background tasks.

**Comment by Hexagon** [comment]
I'm not sure how croner could help with that. Wouldn't it be better to send a signal to the server side, and handle the scheduling there? In that case, croner can help.

If schedules need to be persisted over server restarts, and you run node.js, you should have a look at [breejs](https://github.com/breejs/bree) or something similar.

**Comment by Hexagon** [comment]
Closing this, please reopen if you find a reproducable bug.
