### ISSUE TITLE
Odd minutes

### ISSUE THREAD

**Issue by rounsmith** [Hexagon/croner#206]
Hello,
I haven't found really a solution for odd minutes.

For example i have a script that i want to run every 90 minutes.

Do you have any solution for this?

**Comment by Hexagon** [comment]
Use a cron pattern which runs every 30th minute, and use the `interval` option (check the manual for details) to prevent it from running more often than each 90th minute. The minimum interval could be something between 60 and 90 minutes, 85*60 would give 85 minutes, which would work great.
