### ISSUE TITLE
Syntax error is service wroker

### ISSUE THREAD

**Issue by Nekomajin42** [Hexagon/croner#210]
**Describe the bug**
DevTools: `Uncaught SyntaxError: Unexpected token 'export' (at croner.min.js:1:22841)`

**To Reproduce**
Try to import the script in a service wroker.

Example: 
```
self.importScripts("./croner.min.js");
```

**Expected behavior**
`Cron()` should be available in the worker context.

**System:**
 - OS: Windows
 - Runtime: Chrome
 - Version: 7.0.1

**Comment by Hexagon** [comment]
Not familiar to self.importScripts, but it sounds like it is expecting an UMD module? That is provided by the file croner.umd.min.js.

**Comment by Hexagon** [comment]
Closing this. Please re-open if you continue having problems.
