### ISSUE TITLE
Cron Job doesn't run correctly

### ISSUE THREAD

**Issue by rexdavid** [Hexagon/croner#213]
// Code
const job = Cron("* * * * * *", { interval: 60, protect: true, timezone: 'America/New_York' }, () => { console.log('job') });

The above mentioned job gets stuck and does not execute per specification.

**System:**
 - OS: Linux
 - Runtime Node v18.17.1

**Additional context**
Was working correctly in previous versions of croner

**Comment by Hexagon** [comment]
Will have a look at that :+1:

**Comment by Hexagon** [comment]
Fixed in the development branch, please test by `npm install croner@dev` which will give 7.0.2-dev.0

**Comment by rexdavid** [comment]
@Hexagon  -- working now, thanks for fixing!
