### ISSUE TITLE
L5,6 Day of the Week is not working correctly - L is not a number

### ISSUE THREAD

**Issue by SkylineAventador** [Hexagon/croner#214]
SvelteKit, Vite, Bun - hooks.server.js
Other options such as # are working OK.

<img width="889" alt="Screenshot_1" src="https://github.com/Hexagon/croner/assets/32449642/d4c66206-7690-418c-9266-639e73406545">
<img width="764" alt="Screenshot_2" src="https://github.com/Hexagon/croner/assets/32449642/93757248-bd82-48b4-b2e9-c02d6c30ba6e">

**Comment by Hexagon** [comment]
Will have a look at that 👍

**Comment by SkylineAventador** [comment]
Sorry for off-top but just want to ensure: nicknames such as @yearly are hard bounded to the preset value - 1.1.xxxx 00:00 and can’t be parametrized? Also are there any differences between @yearly and @annualy? Thank you. 😊

**Comment by Hexagon** [comment]
Exactly, have a look at the bortom of this page https://croner.56k.guru/usage/pattern/

By the way, does 5#L,6#L work instead of L5,6 ?

**Comment by Hexagon** [comment]
Fixed in dev by https://github.com/Hexagon/croner/commit/92069e2b0c29edec9625e90effdfb671f2989108

**Comment by SkylineAventador** [comment]
Appreciate your response. Have a nice day 👋
