### ISSUE TITLE
Bug: Increment not work as I expected

### ISSUE THREAD

**Issue by Hexagon** [Hexagon/croner#224]
### Discussed in https://github.com/Hexagon/croner/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **kejiweixun** November  2, 2023</sup>
25 15 2/3 * *

The above expression run at 2023/11/03、2023/11/06 etc, but my expectation is 2023/11/02、2023/11/05 etc.
Croner seems to ignore 2 in 2/3, is this a feature or bug?

Thanks!</div>

**Comment by kejiweixun** [comment]
Yes, `croner@7.0.5-dev.0` works as I expected! Thanks!

**Comment by Hexagon** [comment]
Now released in stable branch `croner@7.0.5`
