### ISSUE TITLE
Storing job constant in mongo Db results in error

### ISSUE THREAD

**Issue by ObaidAshiq** [Hexagon/croner#236]
**Describe the bug**
Storing job inside a document in mongoDb results in this error
Error inserting document: BSONError: Cannot convert circular structure to BSON.
Problem is like when the server restarts the job has lost its value, Therefore trying to put in a documnet in mongoDb, any fixes for this

**To Reproduce**

1. Create a model for mongoDb in backend like this
`export const SyncModel = connection1.model("jobSync", new mongoose.Schema({}, { strict: false }), "jobSync");`
2. Initialize your job
` let scheduledJob: Cron;`
3. Run this on an api call or execute it somehow
`    scheduledJob = Cron(cronPattern, async()=> ScheduleSyncFunction(recurringType,userFullName));
    console.log(scheduledJob);
    try {
      const result = await jobScheduledNautoSyncModel.create(scheduledJob);
      console.log('Document inserted:', result);
    } catch (error) {
      console.error('Error inserting document:', error);
    }`
**Expected behavior**
A way to store this schdeuleJob in mongoDb or to keep the information persistant between server restarts

**System:**
 - OS: [ Windows]
 - Runtime [Node.js]

**Comment by Hexagon** [comment]
Unfortnately croner does not work that way, a job can not be revived from a MongoDB document. I you need to persist state you'd need to handle the pattern, settings, function parameters and state for the sceduled job explicitly using a custom document. Another, simpler way would be to use some of the ready made persistent schedulers like bree (which supports MongoDB as storage).
