### ISSUE TITLE
[Feature Request]: A way to stop all scheduled jobs, but wait for running jobs to complete

### ISSUE THREAD

**Issue by jahands** [Hexagon/croner#237]
Maybe this is possible and I just can't find it in the docs. I'd like to handle SIGTERM gracefully like this:
1. Receive SIGTERM
2. Cancel all future cron runs
3. Wait for any jobs that are currently running to complete
4. Exit application

It would be cool if there was something like this:
`await scheduledJobs.drain()` or something like that

What's the recommended way to do this?

**Comment by Hexagon** [comment]
A graceful shutdown is carried out by iterating over scheduledJobs, running `.stop()` on each of the Jobs.

`.stop()` prevents and further execution and stops the scheduler loop, but does not forcefully stop and running executions.

**Comment by jahands** [comment]
Ah! I see - and the program doesn't terminate until the job is done running - that works!
I was kind of expecting to need a promise that delays SIGTERM signals until all crons are done, but it seems it handles that already.

Would still be nice, I think, to have a stopAndWait() method that returns a promise which resolves when the current execution (if any) is done
