### ISSUE TITLE
nextRun gives wrong result when using L (last day) notation

### ISSUE THREAD

**Issue by mpf82** [Hexagon/croner#253]
**Describe the bug**
When using the L notation, nextRun() / nextRuns() give a wrong result.

**To Reproduce**
```
Today: Thurday, July 11th, 2024
Input: 0 * * * 5L
Output: 12.07.2024, 00:00:00 (= next Friday)
Expected: 26.07.2024, 00:00:00 (= last Friday)
```

This is not limited to Fridays or the #L notation - the result is the same for ``0 * * * FriL``

To reproduce you can use the fiddle linked on the github page: https://jsfiddle.net/hexag0n/hoa8kwsb/

I've also checked with version 8.1.0 and 7.0.0 - both with the same result.

Changing the version to 6.0.0 gives the expected result, so somewhere in between 6.0.0 and 7.0.0 this got broken.

**Comment by Hexagon** [comment]
Does 5#L work? Have you seen https://github.com/Hexagon/croner/releases/tag/7.0.0 ?

**Comment by mpf82** [comment]
Thanks for the reply. Yes ``0 * * * 5#L`` works in croner, however I need to support different cron libraries (cronstrue JS, CronSim Python, to just name a few), and none of them accepts that syntax with the additional ``#`` before the ``L``.

I'm not familiar with the Vixie-cron pattern, but ``5L`` is Quartz syntax, which is supportey by most libraries that support ``L`` as a special character.

Though I guess it's my bad for not looking at your docs more carefully, as you clearly state the use of the ``5#L`` pattern here: https://github.com/Hexagon/croner?tab=readme-ov-file#pattern

**Comment by mpf82** [comment]
Closing, as this is not a bug.
