### ISSUE TITLE
Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by f1sle** [Hexagon/croner#28]
Hello!
I encountered the error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /..../backend/node_modules/croner/package.json

Added line solved the problem:

"exports": {
    **"./package.json": "./package.json",**
    ".": {
      "import": "./src/croner.js",
      "require": "./dist/croner.cjs",
      "browser": "./dist/croner.min.js"
    },

**Comment by Hexagon** [comment]
Fixed in release 4.0.83

https://github.com/Hexagon/croner/releases/tag/4.0.83
