### ISSUE TITLE
Duplicated jobs

### ISSUE THREAD

**Issue by f1sle** [Hexagon/croner#29]
Hello!
I created a cron job to send a POST request to my backend with axios.
I have the following cron setting:
![image](https://user-images.githubusercontent.com/39921649/147889166-29aa764b-e55e-457a-9e5a-8c1524448d3c.png)

There is my function content:
![image](https://user-images.githubusercontent.com/39921649/147889175-8ff84293-4161-45a5-9d8b-937b4c4e3d04.png)

Still get duplicated tasks:
![image](https://user-images.githubusercontent.com/39921649/147889186-759489ec-f88d-41c9-b103-7366cc065439.png)

Could you please help that is going on?

**Comment by Hexagon** [comment]
Interesting! Could you please do a console.log beside checkForNewReviews, like

```javascript
() => {
   console.log(new Date().getTime());
   checkForNewReviews();
}
```
To get a better view of whats going on?

**Comment by f1sle** [comment]
Here you are:
1641157690002
1641157690005
[2022-01-02 13:08:13.541] http: POST /api/reviews/update (3514 ms) 200
[2022-01-02 13:08:14.974] http: POST /api/reviews/update (4917 ms) 200
1641157750000
1641157750000
[2022-01-02 13:09:14.773] http: POST /api/reviews/update (4765 ms) 200
[2022-01-02 13:09:17.014] http: POST /api/reviews/update (7003 ms) 200
1641157810001
1641157810001
[2022-01-02 13:10:15.568] http: POST /api/reviews/update (5560 ms) 200
[2022-01-02 13:10:32.324] http: POST /api/reviews/update (22312 ms) 200
Also a question, does it supposed to run it every 10 seconds? ('10 * * * * *')

**Comment by Hexagon** [comment]
Seems like you accidentaly trigger the scheduling twice, maybe by including the triggering file twice? Croner really should not be able to make duplicate runs like that :)

Yes, if you use six part notation (10 * * * * *) the first part sets seconds, if you use five parts (10 * * * *) the first part sets minutes.

**Comment by f1sle** [comment]
I have already tried three different cron packages (croner, node-cron, node-scheduler), the same problem exists for all of them.

**Comment by f1sle** [comment]
So, with this configuration it runs every minute ('10 * * * * *').
This is really strange.
1641158410001
1641158410001
[2022-01-02 13:20:13.783] http: POST /api/reviews/update (3758 ms) 200
[2022-01-02 13:20:14.496] http: POST /api/reviews/update (4440 ms) 200
1641158470002
1641158470001
[2022-01-02 13:21:14.936] http: POST /api/reviews/update (4927 ms) 200
[2022-01-02 13:21:15.658] http: POST /api/reviews/update (5646 ms) 200

**Comment by Hexagon** [comment]
See my edited comments for pointers, your pattern is supposed to run att second 10 every minute, */10 * * * * * would runt every tenth second

**Comment by Hexagon** [comment]
Did the output of your last comments come when putting console.log outside the triggered function? Like

```
console.log(new Date...);
let job = Cron(...);
```

**Comment by f1sle** [comment]
Nope, this is my exact code:
```
const checkForNewReviews = require("./functions/checkForNewReviews");

var Cron = require("croner");

const job = Cron("*/10 * * * * *", () => {
  console.log(new Date().getTime());
});
```

**Comment by Hexagon** [comment]
Can you try this instead

```
const checkForNewReviews = require("./functions/checkForNewReviews");

var Cron = require("croner");

console.log(new Date().getTime());

const job = Cron("*/10 * * * * *", () => {});
```

And se if you get a duplicate log?

**Comment by f1sle** [comment]
![image](https://user-images.githubusercontent.com/39921649/147890156-e07f1bb4-5d9a-4a01-80ba-1b0a324cda72.png)

![image](https://user-images.githubusercontent.com/39921649/147890149-b0123ae2-3b26-4356-9f34-70d181cf8e95.png)

**Comment by Hexagon** [comment]
Ah, the code in backend/config/cron.js is run twice, for some reason

**Comment by f1sle** [comment]
Okay, thank you for your time.
I'll check that for sure.
Seems like it's a bug of another system :)

**Comment by Hexagon** [comment]
No problem!

**Comment by ObaidAshiq** [comment]
Could it be because u had earlier installed node- cron and then u installed cronner
I am having similar issue
