### ISSUE TITLE
Feature: Schedule at specific date

### ISSUE THREAD

**Issue by Hexagon** [Hexagon/croner#4]
Add possibility to schedule a run at a specific date/time.

**Comment by Hexagon** [comment]
Do se need this? Like ```Cron(new Date(2022,1,2,0,0,0), ()=>{});```

**Comment by anogray** [comment]
> Do se need this? Like ```Cron(new Date(2022,1,2,0,0,0), ()=>{});```

Yes, also need allow to be use Moment time to pass.

**Comment by Hexagon** [comment]
This is work in progress

**Comment by Hexagon** [comment]
@anogray @bhaskarb360
