### ISSUE TITLE
How to schedule cron tab if time is past/expired.

### ISSUE THREAD

**Issue by bhaskarb360** [Hexagon/croner#44]
Say we have current time as 5th Feb 2022 and Time is 15:25:07 while the value of cron is 15:10:10.
How we can handle and execute still that job.
Example as of cron package:
![image](https://user-images.githubusercontent.com/89518767/152636998-2da8d506-8e08-47fc-a28d-f4c4493e5166.png)

**Comment by Hexagon** [comment]
Normally,missed jobs is out of scope for a cron-style runner, but i see that you use CronJob with a specific time point. I am considering to support this in croner, but would recommend you to use a simpler approach, that does not depend on the cron library to throw errors. Something like:

```javascript
if(response[idx].endDate < new Date()) {
   // Immediately run the stuff, without using a cron library
} else {
   // Create a new cron job that execute in the future
   let job = new Cron(pattern, () => { // stuff to run });
}
```

But, i will consider implementing one-off-scheduling using a single point i time. In that case, croner will return null if time is in the past.

**Comment by anogray** [comment]
It seems it is better to have your own setTimeout logic rather than any other open source .😅
