### ISSUE TITLE
Cron job every five months, next not calculated correctly

### ISSUE THREAD

**Issue by AntoninoBonanno** [Hexagon/croner#52]
### Description

Hi 
I'm trying to run a cron every 5 months at 10 am. But the next date is not calculated correctly.

```
const job = new Cron(`0 10 1 */5 *`, {timezone: "Europe/Rome"}, () => {
// My Job
});
console.log((new Date()).toISOString(), job.next()?.toISOString());
```

Output: 
Now: 2022-02-15T09:05:05.829Z
next:  2022-05-01T08:00:00.000Z

I expect the next is: 2022-07-01T08:00:00.000Z

My tests: 
`0 10 1 */1 *` -> (next:  2022-03-01T09:00:00.000Z)

`0 10 1 */2 *` -> (next:  2022-04-01T08:00:00.000Z)

`0 10 1 */3 *` <- Not work (next:  2022-03-01T09:00:00.000Z)

`0 10 1 */4 *` <- Not work (next:  2022-04-01T08:00:00.000Z)

`0 10 1 */5 *` <- Not work (next:  2022-05-01T08:00:00.000Z )

I've also tried setting the startAt option, but it doesn't change anything:
```
{
  startAt: new Date(),
  timezone: "Europe/Rome"
}
```

**Comment by Hexagon** [comment]
Hi!

As wierd as it may sound - that's actually how cron is supposed to work. The range modifier works by selecting the 5th month every year, yielding may and october each year.

If this would work the way you expect, (yielding july when started in february), what would happen if your process crash and restart within four months?

However, there are solutions. If you can live with the problem of postponing on process restart, and can live with the job running ~every 5th month. A simple setInterval should do

```javascript

// Start
let jobId = setInterval( () => {
   console.log('My job');
}, 5*30*24*60*60*1000);

// Stop
// clearInterval( jobId );
```

If you want to have the job execute at a specific date and time every 5th month, you can combine a cron-runner with minor logic.

```javascript
import Cron from 'https://esm.run/croner';

// Helper
const monthDiff = (d1, d2) =>  d2.getMonth() - d1.getMonth() + (12 * (d2.getFullYear() - d1.getFullYear()));

// Process start date
const startedAt = new Date();

// Actual job
const job = Cron('0 10 1 * *', (ctx) => {
   if (monthDiff(startedAt, new Date()) % 5 === 0) {
      console.log('This is executed every 5th months from start date');
  }
});

// Test job
const testJob = Cron('0 10 1 * *').enumerate(20).forEach((currentRun) => {
   if (monthDiff(startedAt, currentRun) % 5 === 0) {
      console.log('Triggered at ' + currentRun.toLocaleString());
   } else {
      console.log('Skipped at ' + currentRun.toLocaleString());
   }
});
```

- @jsFiddle -> https://jsfiddle.net/12Lnpou0/1/

Output from test job
```
Skipped at 2022-03-01 10:00:00
Skipped at 2022-04-01 10:00:00
Skipped at 2022-05-01 10:00:00
Skipped at 2022-06-01 10:00:00
Triggered at 2022-07-01 10:00:00
Skipped at 2022-08-01 10:00:00
Skipped at 2022-09-01 10:00:00
Skipped at 2022-10-01 10:00:00
Skipped at 2022-11-01 10:00:00
Triggered at 2022-12-01 10:00:00
Skipped at 2023-01-01 10:00:00
Skipped at 2023-02-01 10:00:00
Skipped at 2023-03-01 10:00:00
Skipped at 2023-04-01 10:00:00
Triggered at 2023-05-01 10:00:00
Skipped at 2023-06-01 10:00:00
Skipped at 2023-07-01 10:00:00
Skipped at 2023-08-01 10:00:00
Skipped at 2023-09-01 10:00:00
Triggered at 2023-10-01 10:00:00
```

**Comment by AntoninoBonanno** [comment]
Thanks, I consider the second solution (combine a cron-runner with minor logic).
