### ISSUE TITLE
Feature request: Named schedules

### ISSUE THREAD

**Issue by Bengeljo** [Hexagon/croner#57]
Hey I am trying to create multiple schedules for a discord bot.
The user can choose on which date they want to schedule the command, that will get saved in the database if the bot turns off cause of an update or what ever reason. 
The database will then get requested every 10 minutes to check if a new schedule has been add to the database.
So I try to call it and create multiple schedules based on that but your croner seems like it can only run if I say that it has a variable to it, 
or did I missunderstood the documentation.

**Comment by Hexagon** [comment]
Not sure of I understand the problem properly. But what you are trying to do should certainly be possible. 

Can you provide a snippet showing your problem?

**Comment by Hexagon** [comment]
@Bengeljo

**Comment by Bengeljo** [comment]
Sorry I hadn't had time to respond.

So my problem is that I need to have the schedules while they shouldn't stack up. 
Atm I am still using node-schedule but I am looking for an alternativ.
I will add a image to this so you can see what I mean.

The name of the schedule is always the same and when I check for the current schedules I only see one but when he executes, it executes multiple times. If I try to cancel it with the name, that wouldn't be possible since the schedules get set with the servers that requested a scheduled executing of the command and the list is to fast to go through it.
![Failure](https://user-images.githubusercontent.com/86926513/155878347-7f7c073c-46a6-4e11-b41f-f774927d5bdf.PNG)

I need to look often for a new schedule like every 10 minutes that is why it probably stacks up. In the image he is checking every 10 seconds just so I can be sure that the code works like I want it cause in the long run it will also stack up. 

I will try to implement your extantion and experiment with it but I have the fear that it won't work as well since I can't seem to name it or make it in anyways uniqe to a server.

**Comment by Hexagon** [comment]
I think I understand now. You want to store a couple of named schedules in a database, and you want to update your schedules periodically from the database?

Pseudecode:
```javascript

const Cron = require('croner'),
          db = require('./db.js'),

          namedCronInstances = [];

// Every 10th minute, check database for all schedules
Cron('0 */10 * * * *'', () => {
   checkDataBaseForSchedules();
});

function checkDataBaseForSchedules() {
   db.fetchAllSchedules((schedule) => {
     // Stop schedule if schedule already exists
     if (namedCronInstances[schedule.name]) {
        console.log('Stopping '+ schedule.name;
       namedCronInstances[schedule.name].stop();
    }

   // Start new/updated schedule
   console.log('Starting ' + schedule.name);
   namedCronInstasnces[schedule.name] = Cron(schedule.pattern, () => {
      console.log('Running ' + schedule.name);

      // OPTIONAL: Delete schedule from database when executed
      db.deleteSchedule(schedule.name);
   });
 });
}
````

**Comment by Bengeljo** [comment]
Exactly what I am looking for.
When the schedule executes can I access the name with schedule.name? 
If yes I will try to implement it as fast as possible into my code, cause I save specific information into the name that I need when it should execute a function.

But beside that question that is exactly what I am looking for, thanks

**Comment by Hexagon** [comment]
Yes, that is possible too. I have updated the example to pass the fictinal `schedule`-object as a context to the triggered function. 

See https://github.com/hexagon/croner#passing-a-context .

**Comment by Bengeljo** [comment]
How did you set up the db.js ? 

If I try to run it with fetchAllschedules it crashes on me cause the database doesn't support .fetch or .fetchAll
