### ISSUE TITLE
This expression is not callable

### ISSUE THREAD

**Issue by albertosantini** [Hexagon/croner#75]
Thanks for your efforts. Here replacing `cron` package with `croner`.
I saw also `PM2` recently migrated to `croner`. Congrats.

Using  `croner 4.3.6`, with `VSCode 1.65.2`, I noted this messages in Problems panel:

```
This expression is not callable.
  Type 'typeof import("[...]/node_modules/croner/types/croner.single")' has no call signatures.

A function with a name starting with an uppercase letter should only be used as a constructor.
```

```
const Cron = require("croner");

Cron("1 25 5 * * *", {
    timezone: "Europe/Rome"
}, () => {
    run();
});
```

Ok, eslint error depends on `new-cap` setting.
The surprise was about ts lint message

Of course I can suppress the messages with the following directives:

```
// @ts-ignore
Cron("1 25 5 * * *", { // eslint-disable-line
    timezone: "Europe/Rome"
}, () => {
    run();
});
```

Any hint?

**Comment by Hexagon** [comment]
Will have a look at that until next release! The typescript definitions isn't widely used yet, i think. So all issue reports are appreciated! 👍

**Comment by Hexagon** [comment]
@albertosantini I just got an idea, if you use `new Cron` instead of just `Cron`, do the message disappear? Cron without new is just a shortcut.

**Comment by albertosantini** [comment]
Yes, it is gone but

`Do not use 'new' for side effects.` due to `no-new` setting.

Sorry. I have been using a quite strict  configuration:
https://github.com/eslint/eslint/blob/main/packages/eslint-config-eslint/default.yml

Resolved with

```
const cron = require("croner");

// @ts-ignore
cron("1 25 5 * * *", {
    timezone: "Europe/Rome"
}, () => {
    run();
});
```

**Comment by Hexagon** [comment]
Just tested it myself, and this is a tricky one. Will consider changing the interface to support such strict rules from 5.0. But for now, I added a note under https://github.com/Hexagon/croner#installation. Thanks again!
