### ISSUE TITLE
Incorrect handling of comma-separated values with ranges and/or stepping

### ISSUE THREAD

**Issue by egfx-notifications** [Hexagon/croner#78]
Hi, I'm currently evaluating cron-related libraries for usage in my project, including reviewing the code of any candidates before deciding which one to use.
Let me first say that I'm very pleased with the quality of your code and that I'm very likely to choose this project to handle cron schedules in my application.

During code review I stumbled upon a few lines regarding the handling of a pattern which as far as I know reject patterns that would be perfectly valid in cron syntax and would also successfully parse by just removing those checks. These lines were introduced with https://github.com/Hexagon/croner/commit/62c0289864ecd0905b75927832f85591e6c3a771

https://github.com/Hexagon/croner/blob/12cc992652a4fb3a080893c47915a2fb59b1625f/src/pattern.js#L141-L163

As you can see in the snippet above, in the function `CronPattern.partToArray()` you first split parts of the current pattern part by comma, but then reject any ranges or steppings if they are evaluated after this split, in the recursion. Contrary to the statement of the thrown error, comma-separated values can perfectly coexist with ranges and stepping. 

I entered the examples from your tests for Cronitor and it parses well:
[https://crontab.guru/#1,2/5_*_*_*_*](https://crontab.guru/#1,2/5_*_*_*_*)
[https://crontab.guru/#1-15/5,6_*_*_*_*](https://crontab.guru/#1-15/5,6_*_*_*_*)
[https://crontab.guru/#1-15,17_*_*_*_*](https://crontab.guru/#1-15,17_*_*_*_*)

As you can see from the website's explanation these patterns are perfectly fine and if you'd just remove those checks they would indeed parse as intended. Actually you could get rid of the `recursed` parameter altogether.

Is there any reason I didn't see yet why you reject such patterns? If you want to accept these patterns as Cronitor does, I can submit a PR as I already made some tests locally. Just want to hear your opinion on it first.

**Comment by Hexagon** [comment]
Sounds like a great fix, and something i just haven't thought of. 

Submit the PR when you're happy with it, and I'll have a deeper look asap 👍

**Comment by Hexagon** [comment]
Great finding, and great work. Thanks!

Released in [4.3.8](https://github.com/Hexagon/croner/releases/tag/4.3.8)

**Comment by Hexagon** [comment]
@egfx-notifications 

One additional note, since you mention crontab.guru. 

It seems like this site use standard mode when combining day-of-month with day-of-week. Croner works a bit different by default, which I've explained at [#53](https://github.com/Hexagon/croner/issues/53). I am considering to change default behavior on next major release, but for now you need to use option `legacyMode: true`.

**Comment by egfx-notifications** [comment]
Yes, I noticed that during review, but thanks for pointing it out :)
