### ISSUE TITLE
Feature: Pattern with range and stepping

### ISSUE THREAD

**Issue by gilles-crealp** [Hexagon/croner#8]
It would be nice if we could use a pattern made of a range and a stepping.

Example: [`15-45/10 * * * *`](https://crontab.guru/#15-45/10_*_*_*_*) = xx:15, xx:25, xx:35 & xx:45.

**Comment by Hexagon** [comment]
Very doable, do you want tog give it a try yourself? Noticed that you made a fork :)

**Comment by Hexagon** [comment]
@gilles-crealp Implemented in https://github.com/Hexagon/croner/commit/227e975adc95827c4a752b9689f8a815fef768a6, it did not turn out exactly like you described it, but pretty close.

```15-45/10``` will run 20,30,40 as those are the points in time common to both ```*/10``` and ```15-45```. I think that is the most logical implementation. What do you think?

```0-15/2``` will run at 0,2,4,6,8,10,12,14 of the same reason.

```15-45/15``` will run at 15,30,45

**Comment by gilles-crealp** [comment]
> `15-45/10` will run 20,30,40 as those are the points in time common to both `*/10` and `15-45`. I think that is the most logical implementation. What do you think?

Sorry to disagree but you cannot implement like this because it's limitating (and not standard).

With your solution, you cannot have :15, :25, :35, :45 who sould be `15-45/10`. :20, :30, :40 sould be `20-45/10`.

**Comment by Hexagon** [comment]
Didn't kmow there is a standard to it. But now i know better. Will have a look att pulling your solution tonight 👍

**Comment by gilles-crealp** [comment]
> Didn't kmow there is a standard to it.

https://www.ibm.com/docs/en/db2oc?topic=task-unix-cron-format#d64579e309

**Comment by Hexagon** [comment]
@gilles-crealp Released in 4.0,76 👍
